name: food_app_comps
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.15.1 <3.0.0'
dependencies: 
  auto_size_text: 3.0.0
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: 
  assets: 
    - assets/images/
    - packages/food_app_comps/assets/images/1_13.png
    - packages/food_app_comps/assets/images/1_15.png
    - packages/food_app_comps/assets/images/1_14.png
    - packages/food_app_comps/assets/images/1_16.png
    - packages/food_app_comps/assets/images/1_17.png
    - packages/food_app_comps/assets/images/1_19.png
    - packages/food_app_comps/assets/images/1_18.png
    - packages/food_app_comps/assets/images/1_4.png
    - packages/food_app_comps/assets/images/1_7.png
  uses-material-design: true
